# -*- coding: utf-8 -*-
"""Student_Performance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1toJDemzvNqVBzzehP1XFJ1sfRuY3t7h8

**Problem Statement: Student Performance Prediction using Decision Tree**
"""

#Step 1: Imported the necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

#Step 2:Imported the dataset
df = pd.read_csv('StudentPerformance.csv')

#Step 3: Exploratry Data Analysis(EDA)
#Check is there any missing value as decision tree do not
#handle missing values
print(df.isnull().sum())

# Replace the missing values in numerical columns with the median
df['Study Hours per Week'] = df['Study Hours per Week'].fillna(df['Study Hours per Week'].median())
df['Attendance Rate'] = df['Attendance Rate'].fillna(df['Attendance Rate'].median())
df['Previous Grades'] = df['Previous Grades'].fillna(df['Previous Grades'].median())

# We will drop rows where 'Passed' is missing as it's our target variable for classification
df.dropna(subset=['Passed'], inplace=True)

# Verify that there are no more missing values
print(df.isnull().sum())

# Step 4: Data Encoding
'''
 Many datasets contain non-numeric data which cannot be handled by the alogrithm
 so we have to convert non-numeric data into numeric data.
 In our case the passed column contain string values YES & NO, which we have to
 convert it into numerical values.
 '''
# Convert 'Passed' column to numerical (1 for 'Yes', 0 for 'No')
df['Passed'] = df['Passed'].map({'Yes': 1, 'No': 0})
display(df.head())

# Step 5: Feature and Target Selection
X = df[['Study Hours per Week', 'Attendance Rate', 'Previous Grades']]
y = df['Passed']

# Display the first few rows of X and y to confirm
print("Features (X):")
display(X.head())
print("\nTarget (y):")
display(y.head())

# Step 6 : Train-Test split
'''
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
here test size means the size of the testing data which is 0.2(20%) and the
remaining 80% data is used for training the model.
Random state means the number of times we shuffle our data, here 42 times.
'''
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 7: Creating an object and training the model.
model = DecisionTreeClassifier(max_depth=5)
model.fit(X_train, y_train)

# Step 8: Make prediction on the unseen data
y_predict = model.predict(X_test)
print(y_predict)
# Here only predicting the exam scores for the 5 rows

# Step 9: Evaluating the model for classification
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print('Accuracy Score:', accuracy_score(y_test, y_predict))
print('\nConfusion Matrix:\n', confusion_matrix(y_test, y_predict))
print('\nClassification Report:\n', classification_report(y_test, y_predict))

#Step 9: Visulaizing the decision tree
plt.figure(figsize=(20,10))
tree.plot_tree(model, feature_names=X.columns, class_names=['Failed', 'Passed'], filled=True, rounded=True, max_depth=3)
plt.title('Decision Tree Visualization (Truncated to Depth 3)')
plt.show()